### ISSUE TITLE
About the dropped http plugins support

### ISSUE THREAD

**Issue by MoisesDuarte** [tachibana-shin/vue-auth3#10]
Would it be possible to reinstate the use of the { plugins: { http: AxiosInstance } } option to pass the local axios instance instead of the driver as an optional configuration option?

I'm asking because I'm working with a legacy frontend that we are now refactoring to vue 3 with quasar and it would help a lot to have the option to use the local axios config, since we have a lot of logic pertaining to the way our auth services are called (headers that are dynamically changed by store, etc). The lib is proving very good with typescript, so we would like to use in lieu of websanova/vue-auth if possible.

**Comment by tachibana-shin** [comment]
Is this what you mean?
```ts
const api = axios.create({....})

const auth = createAuth({
    drivers: {
      http: {
        request: api,
      },
      ...
    }
    ...
})
```

If so then this plugin was designed from the ground up so it's ready now

**Comment by tachibana-shin** [comment]
or if you don't like `axios` you also have an option to use `fetch`

**Comment by MoisesDuarte** [comment]
Oh, I'm sorry then. I must have not seen it in the documentation. Passing the api here seems to work initially, I will be testing out it. Sorry for the confusion. Thanks for the package by the way, we would have a hard time trying to adapt the old one for our needs.
