### ISSUE TITLE
createAuth is not a function error

### ISSUE THREAD

**Issue by enzortk** [tachibana-shin/vue-auth3#13]
import "./style.css";
import App from "./App.vue";
import router from "./routes";
import { createAuth } from "vue-auth3";

import driverAuthBasic from "vue-auth3/drivers/auth/basic";
import driverHttpAxios from "vue-auth3/drivers/http/axios";

const auth = createAuth({
    plugins: {
        router,
    },
    drivers: {
        auth: driverAuthBasic,
        http: driverHttpAxios,
    },
})

createAuth.use(router).use(auth).mount("#app")

this code gives me main.ts:20 Uncaught TypeError: auth.use is not a function

**Comment by tachibana-shin** [comment]
like the bot explained what you need is `createApp` of vue and not `use` of `vue-auth3`

**Comment by JarradWilder** [comment]
The docs had a mistake in the example for the App.vue file. I created an MR to correct the code example

**Comment by tachibana-shin** [comment]
Thanks for PR! https://github.com/tachibana-shin/vue-auth3/pull/14
