### ISSUE TITLE
Error with Quasar (ts) + vite 

### ISSUE THREAD

**Issue by Pok09** [tachibana-shin/vue-auth3#2]
When import driverAuthBearer from 'vue-auth3/dist/drivers/auth/bearer', on boot

[vite] Internal server error: Missing "./dist/drivers/auth/bearer" export in "vue-auth3" package

**Comment by tachibana-shin** [comment]
hello what version of quasar are you using?

**Comment by ArtyomBist** [comment]
the same error with vue3/vuetify 3 and vite

**Comment by ArtyomBist** [comment]
I think it problem related with Vite https://github.com/vitejs/vite/issues/1505

**Comment by tachibana-shin** [comment]
a workaround has been mentioned here: https://github.com/tachibana-shin/vue-auth3/issues/3

**Comment by tachibana-shin** [comment]
> I think it problem related with Vite [vitejs/vite#1505](https://github.com/vitejs/vite/issues/1505)

thanks for the info i didn't notice it was part of the truncation from `vite`
