### ISSUE TITLE
"Remember me" or "Remember data"

### ISSUE THREAD

**Issue by ismailarilik** [tachibana-shin/vue-auth3#39]
![image](https://github.com/tachibana-shin/vue-auth3/assets/17585121/032b5ed3-c490-4647-aa81-f46113c97464)

The type of `remember` option for login and register is boolean but in some places, this is referred as a string type. What is the correct purpose and type of this option?

Also related: https://vue-auth3.js.org/methods/utils.html#remember

**Comment by tachibana-shin** [comment]
remember is of type `boolean` to determine whether the information will be stored the next time it is accessed. The `remember()` function can handle a string type but is normally a hack and should not be used

**Comment by ismailarilik** [comment]
Thank you. I am gonna update the docs and open a PR for it.
