### ISSUE TITLE
Getting user data in the notFoundRedirect callback

### ISSUE THREAD

**Issue by Secular12** [tachibana-shin/vue-auth3#63]
I am trying to dynamically choose where to redirect a user based on their user/role. However I cannot use `useUser` inside of the callback as it has an inject (assuming the store) that has to be used inside the setup. But doing it inside of setup doesn't work since `definePage` runs before useUser is registered in the setup. Any suggestions? Is there a way that the user data could exist in the `transition`?

```js
<script lang="ts" setup>
import { userUser } from 'vue-auth3'

definePage({
  meta: {
    auth: {
      roles: false,
      notFoundRedirect: (transition: any) => {
        const authUser = useUser().value
        console.log(authUser)
      }
    },
  },
})
</script>
```

**Comment by tachibana-shin** [comment]
Use `auth.user()`

**Comment by Secular12** [comment]
> Use `auth.user()`

Which "auth" should I be using that from? Because if I switch out `useUser` for `useAuth` I still get this error: `[Vue warn]: inject() can only be used inside setup() or functional components.`

```js
<script lang="ts" setup>
import { userAuth } from 'vue-auth3'

definePage({
  meta: {
    auth: {
      roles: false,
      notFoundRedirect: (transition: any) => {
        const auth = userAuth()
        const authUser = auth.user()
        console.log(authUser)
      }
    },
  },
})
</script>
```

Is there another way to get auth from inside of the notFoundRedirect? I cannot declare it outside of the `definePage` because that gets called before any of the rest of `setup` is called.

**Comment by Secular12** [comment]
Is there a chance that the user could be passed into the `transition` parameter?

**Comment by tachibana-shin** [comment]
> Is there a chance that the user could be passed into the `transition` parameter?

Do you have `createAuth`? `auth = createAuth({...})`

**Comment by Secular12** [comment]
> > Is there a chance that the user could be passed into the `transition` parameter?
> 
> Do you have `createAuth`? `auth = createAuth({...})`

Using the createAuth returned from the plugin worked. Thank you. I am not sure why I was not thinking to use it in this way.
